# syntax=docker/dockerfile:1

FROM rust:bookworm
RUN apt-get update \
    && apt-get install -y --no-install-recommends pkg-config libssl-dev curl \
    && rm -rf /var/lib/apt/lists/* \
    && cargo install cargo-tarpaulin --locked
WORKDIR /src
ENTRYPOINT ["/bin/sh", "-ec"]
