/// Minecraft EULA text required in server data directory.
pub const EULA_TEXT: &str = "# By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).\n# Generated by minecraft-k8s\neula=true\n";

/// Returns EULA file contents when accepted.
pub fn render_eula(accepted: bool) -> crate::error::Result<String> {
    if accepted {
        Ok(EULA_TEXT.to_string())
    } else {
        Err(crate::error::AppError::EulaNotAccepted)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::AppError;

    #[test]
    fn render_when_accepted() {
        let text = render_eula(true).unwrap();
        assert!(text.contains("eula=true"));
    }

    #[test]
    fn render_when_not_accepted() {
        assert_eq!(render_eula(false).unwrap_err(), AppError::EulaNotAccepted);
    }
}
